use anyhow::{bail, Context, Result};
use radar_core::diff::DiffChange;
use radar_core::models::Severity;
use reqwest::header::{HeaderMap, HeaderValue, ACCEPT, AUTHORIZATION, USER_AGENT};
use serde::{Deserialize, Serialize};
use std::env;

// Marker embedded in every drift comment so we can find and update it.
const COMMENT_MARKER: &str = "<!-- radar-monitor-report -->";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
pub struct GithubContext {
    pub token: String,
    pub owner: String,
    pub repo: String,
    pub pr_number: u64,
}

impl GithubContext {
    /// Detect GitHub context from CI environment variables.
    /// Returns None if not running in a GitHub Actions PR context.
    pub fn from_env() -> Option<Self> {
        let token = env::var("GITHUB_TOKEN").ok()?;

        let repo_env = env::var("GITHUB_REPOSITORY").ok()?;
        let mut parts = repo_env.splitn(2, '/');
        let owner = parts.next()?.to_string();
        let repo = parts.next()?.to_string();

        // Detect PR number from multiple sources, in priority order.
        let pr_number = detect_pr_number()?;

        Some(GithubContext {
            token,
            owner,
            repo,
            pr_number,
        })
    }
}

/// Try to detect a PR number from the environment, in order:
/// 1. `GITHUB_PR_NUMBER` (explicit override)
/// 2. `GITHUB_REF` like `refs/pull/42/merge`
/// 3. `GITHUB_EVENT_PATH` JSON file, `.pull_request.number`
fn detect_pr_number() -> Option<u64> {
    // 1. Explicit env var
    if let Ok(val) = env::var("GITHUB_PR_NUMBER") {
        if let Ok(n) = val.trim().parse::<u64>() {
            return Some(n);
        }
    }

    // 2. Parse refs/pull/{n}/merge from GITHUB_REF
    if let Ok(github_ref) = env::var("GITHUB_REF") {
        if let Some(n) = parse_pr_from_ref(&github_ref) {
            return Some(n);
        }
    }

    // 3. Parse GITHUB_EVENT_PATH JSON
    if let Ok(event_path) = env::var("GITHUB_EVENT_PATH") {
        if let Ok(contents) = std::fs::read_to_string(&event_path) {
            if let Ok(value) = serde_json::from_str::<serde_json::Value>(&contents) {
                if let Some(n) = value
                    .get("pull_request")
                    .and_then(|pr| pr.get("number"))
                    .and_then(|n| n.as_u64())
                {
                    return Some(n);
                }
            }
        }
    }

    None
}

fn parse_pr_from_ref(github_ref: &str) -> Option<u64> {
    // refs/pull/42/merge
    let stripped = github_ref.strip_prefix("refs/pull/")?;
    let num_str = stripped.split('/').next()?;
    num_str.parse::<u64>().ok()
}

// ---------------------------------------------------------------------------
// Comment building
// ---------------------------------------------------------------------------

/// Build the Markdown comment body from the diff results.
pub fn build_comment(
    changes: &[DiffChange],
    from_ref: &str,
    to_ref: &str,
    policy_verdict: &str,
) -> String {
    if changes.is_empty() {
        return format!(
            "{marker}\n## \u{2705} Radar Monitor \u{2014} No API Changes\n\nNo schema changes detected between `{from_ref}` and `{to_ref}`.\n",
            marker = COMMENT_MARKER,
        );
    }

    let breaking = changes
        .iter()
        .filter(|c| c.severity == Severity::Breaking)
        .count();
    let risky = changes
        .iter()
        .filter(|c| c.severity == Severity::NonBreakingRisky)
        .count();
    let safe = changes
        .iter()
        .filter(|c| c.severity == Severity::Safe)
        .count();

    let mut rows = String::new();
    for change in changes {
        let emoji = severity_emoji(&change.severity);
        let label = severity_label(&change.severity);
        let kind = kind_label(&change.kind);
        rows.push_str(&format!(
            "| {emoji} **{label}** | `{}` | `{kind}` |\n",
            change.path
        ));
    }

    format!(
        "{marker}\n\
## \u{1f50d} Radar Monitor \u{2014} API Contract Check\n\n\
Comparing `{from_ref}` \u{2192} `{to_ref}`\n\n\
| Severity | Path | Change |\n\
|---|---|---|\n\
{rows}\n\
---\n\
**{breaking} breaking** \u{00b7} **{risky} risky** \u{00b7} **{safe} safe**\n\n\
> {policy_verdict}\n\n\
<sub>Generated by [Radar Monitor](https://github.com) v0.1.0</sub>\n",
        marker = COMMENT_MARKER,
    )
}

fn severity_emoji(severity: &Severity) -> &'static str {
    match severity {
        Severity::Breaking => "\u{1f534}",        // 🔴
        Severity::NonBreakingRisky => "\u{1f7e1}", // 🟡
        Severity::Safe => "\u{1f7e2}",             // 🟢
    }
}

fn severity_label(severity: &Severity) -> &'static str {
    match severity {
        Severity::Breaking => "BREAKING",
        Severity::NonBreakingRisky => "Risky",
        Severity::Safe => "Safe",
    }
}

fn kind_label(kind: &radar_core::models::ChangeKind) -> &'static str {
    use radar_core::models::ChangeKind;
    match kind {
        ChangeKind::FieldRemoved => "field_removed",
        ChangeKind::FieldAdded => "field_added",
        ChangeKind::TypeChanged => "type_changed",
        ChangeKind::RequiredChanged => "required_changed",
        ChangeKind::OperationRemoved => "operation_removed",
        ChangeKind::OperationAdded => "operation_added",
        ChangeKind::ParameterRemoved => "parameter_removed",
        ChangeKind::ResponseRemoved => "response_removed",
        ChangeKind::EnumValueRemoved => "enum_value_removed",
        ChangeKind::EnumValueAdded => "enum_value_added",
        ChangeKind::NullabilityChanged => "nullability_changed",
        ChangeKind::RequestBodyAdded => "request_body_added",
        ChangeKind::RequestBodyRemoved => "request_body_removed",
    }
}

// ---------------------------------------------------------------------------
// GitHub API interaction
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct CommentResponse {
    id: u64,
    body: String,
}

#[derive(Serialize)]
struct CommentBody<'a> {
    body: &'a str,
}

#[derive(Deserialize)]
struct CreatedComment {
    html_url: String,
}

/// Post or update (idempotent) the drift comment on the PR.
/// Returns the comment URL on success.
pub async fn post_or_update_comment(ctx: &GithubContext, body: &str) -> Result<String> {
    let mut default_headers = HeaderMap::new();
    default_headers.insert(
        USER_AGENT,
        HeaderValue::from_static("radar-monitor/0.1"),
    );

    let client = reqwest::Client::builder()
        .default_headers(default_headers)
        .build()
        .context("failed to build HTTP client")?;

    let auth_value = format!("Bearer {}", ctx.token);
    let auth_header =
        HeaderValue::from_str(&auth_value).context("invalid GITHUB_TOKEN value")?;

    // List existing comments on the PR.
    let list_url = format!(
        "https://api.github.com/repos/{}/{}/issues/{}/comments?per_page=100",
        ctx.owner, ctx.repo, ctx.pr_number
    );

    let list_resp = client
        .get(&list_url)
        .header(AUTHORIZATION, auth_header.clone())
        .header(ACCEPT, "application/vnd.github+json")
        .send()
        .await
        .context("failed to list PR comments")?;

    if !list_resp.status().is_success() {
        let status = list_resp.status();
        let text = list_resp
            .text()
            .await
            .unwrap_or_else(|_| "<unreadable>".into());
        bail!("GitHub API error listing comments: {} — {}", status, text);
    }

    let comments: Vec<CommentResponse> = list_resp
        .json()
        .await
        .context("failed to parse comment list response")?;

    let existing = comments.iter().find(|c| c.body.starts_with(COMMENT_MARKER));

    let response_body = if let Some(existing_comment) = existing {
        // PATCH to update the existing comment.
        let patch_url = format!(
            "https://api.github.com/repos/{}/{}/issues/comments/{}",
            ctx.owner, ctx.repo, existing_comment.id
        );
        let resp = client
            .patch(&patch_url)
            .header(AUTHORIZATION, auth_header)
            .header(ACCEPT, "application/vnd.github+json")
            .json(&CommentBody { body })
            .send()
            .await
            .context("failed to update PR comment")?;

        if !resp.status().is_success() {
            let status = resp.status();
            let text = resp.text().await.unwrap_or_else(|_| "<unreadable>".into());
            bail!("GitHub API error updating comment: {} — {}", status, text);
        }

        resp
    } else {
        // POST a new comment.
        let post_url = format!(
            "https://api.github.com/repos/{}/{}/issues/{}/comments",
            ctx.owner, ctx.repo, ctx.pr_number
        );
        let resp = client
            .post(&post_url)
            .header(AUTHORIZATION, auth_header)
            .header(ACCEPT, "application/vnd.github+json")
            .json(&CommentBody { body })
            .send()
            .await
            .context("failed to post PR comment")?;

        if !resp.status().is_success() {
            let status = resp.status();
            let text = resp.text().await.unwrap_or_else(|_| "<unreadable>".into());
            bail!("GitHub API error posting comment: {} — {}", status, text);
        }

        resp
    };

    let created: CreatedComment = response_body
        .json()
        .await
        .context("failed to parse comment response")?;

    Ok(created.html_url)
}

// ---------------------------------------------------------------------------
// D-2: Label check
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct LabelItem {
    name: String,
}

/// Return true if the PR has a label with the given exact name.
/// Silently returns false on any network/parse error.
pub async fn pr_has_label(ctx: &GithubContext, label: &str) -> bool {
    let mut default_headers = HeaderMap::new();
    default_headers.insert(USER_AGENT, HeaderValue::from_static("radar-monitor/0.1"));

    let client = match reqwest::Client::builder()
        .default_headers(default_headers)
        .build()
    {
        Ok(c) => c,
        Err(_) => return false,
    };

    let auth_value = format!("Bearer {}", ctx.token);
    let auth_header = match HeaderValue::from_str(&auth_value) {
        Ok(h) => h,
        Err(_) => return false,
    };

    let url = format!(
        "https://api.github.com/repos/{}/{}/issues/{}/labels",
        ctx.owner, ctx.repo, ctx.pr_number
    );

    let resp = match client
        .get(&url)
        .header(AUTHORIZATION, auth_header)
        .header(ACCEPT, "application/vnd.github+json")
        .send()
        .await
    {
        Ok(r) => r,
        Err(_) => return false,
    };

    if !resp.status().is_success() {
        return false;
    }

    let labels: Vec<LabelItem> = match resp.json().await {
        Ok(l) => l,
        Err(_) => return false,
    };

    labels.iter().any(|l| l.name == label)
}

// ---------------------------------------------------------------------------
// D-3: GitHub Release posting
// ---------------------------------------------------------------------------

#[derive(Serialize)]
struct CreateReleaseBody<'a> {
    tag_name: &'a str,
    name: &'a str,
    body: &'a str,
    draft: bool,
    prerelease: bool,
}

#[derive(Deserialize)]
struct ReleaseResponse {
    html_url: String,
}

/// Create a GitHub Release tagged `tag_name` with the given body.
/// Returns the release URL on success.
pub async fn post_release(
    ctx: &GithubContext,
    tag_name: &str,
    title: &str,
    body: &str,
) -> Result<String> {
    let mut default_headers = HeaderMap::new();
    default_headers.insert(USER_AGENT, HeaderValue::from_static("radar-monitor/0.1"));

    let client = reqwest::Client::builder()
        .default_headers(default_headers)
        .build()
        .context("failed to build HTTP client")?;

    let auth_value = format!("Bearer {}", ctx.token);
    let auth_header =
        HeaderValue::from_str(&auth_value).context("invalid GITHUB_TOKEN value")?;

    let url = format!(
        "https://api.github.com/repos/{}/{}/releases",
        ctx.owner, ctx.repo
    );

    let resp = client
        .post(&url)
        .header(AUTHORIZATION, auth_header)
        .header(ACCEPT, "application/vnd.github+json")
        .json(&CreateReleaseBody {
            tag_name,
            name: title,
            body,
            draft: false,
            prerelease: false,
        })
        .send()
        .await
        .context("failed to create GitHub Release")?;

    if !resp.status().is_success() {
        let status = resp.status();
        let text = resp.text().await.unwrap_or_else(|_| "<unreadable>".into());
        bail!("GitHub API error creating release: {} — {}", status, text);
    }

    let release: ReleaseResponse = resp
        .json()
        .await
        .context("failed to parse release response")?;

    Ok(release.html_url)
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use radar_core::{
        diff::DiffChange,
        models::{ChangeKind, Severity},
    };

    fn sample_changes() -> Vec<DiffChange> {
        vec![
            DiffChange {
                path: "GET /users".into(),
                kind: ChangeKind::OperationRemoved,
                severity: Severity::Breaking,
                description: None,
            },
            DiffChange {
                path: "POST /users".into(),
                kind: ChangeKind::OperationAdded,
                severity: Severity::Safe,
                description: None,
            },
        ]
    }

    #[test]
    fn comment_contains_marker() {
        let body = build_comment(&sample_changes(), "abc", "def", "Policy: active_consumers");
        assert!(body.starts_with(COMMENT_MARKER));
    }

    #[test]
    fn empty_changes_produces_success_message() {
        let body = build_comment(&[], "abc", "def", "Policy: never");
        assert!(body.contains("No API Changes"));
    }

    #[test]
    fn comment_contains_breaking_emoji() {
        let body = build_comment(&sample_changes(), "abc", "def", "Policy: any_break");
        assert!(body.contains("\u{1f534}")); // 🔴
    }

    #[test]
    fn parse_pr_from_ref_extracts_number() {
        assert_eq!(parse_pr_from_ref("refs/pull/42/merge"), Some(42));
        assert_eq!(parse_pr_from_ref("refs/heads/main"), None);
        assert_eq!(parse_pr_from_ref("refs/pull/123/head"), Some(123));
    }

    #[test]
    fn empty_changes_comment_starts_with_marker() {
        let body = build_comment(&[], "sha1", "sha2", "Policy: never");
        assert!(body.starts_with(COMMENT_MARKER));
    }

    #[test]
    fn non_breaking_risky_gets_yellow_emoji() {
        let changes = vec![DiffChange {
            path: "GET /users/{id} \u{2192} param.filter".into(),
            kind: ChangeKind::RequiredChanged,
            severity: Severity::NonBreakingRisky,
            description: None,
        }];
        let body = build_comment(&changes, "abc", "def", "Policy: active_consumers");
        assert!(body.contains("\u{1f7e1}")); // 🟡
    }
}
