[package]
name = "drift-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "drift_core"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
openapiv3 = { workspace = true }
serde_yaml = { workspace = true }
indexmap = { workspace = true }
graphql-parser = "0.4"
